### PR TITLE
add support for ** globs

### PR DESCRIPTION
**Pull request by rmrustem**

### CODE REVIEW

**Comment by joe-elliott** [comment]
@rmrustem thanks for the contribution.  Things generally look fine to me.  Do you know anything more about that filepath glob repo you referenced?  It looks fairly abandoned.

**Comment by rmrustem** [comment]
@joe-elliott it does indeed. Please suggest if it makes sense to include the glob parsing thing into the PR. Meanwhile I'll try to contact the guy behind the glob repo.

**Comment by joe-elliott** [comment]
Yeah, i'm also concerned there is no `LICENSE` in the root.  If you don't mind updating to use this package:

https://github.com/bmatcuk/doublestar

I will merge and build.

**Comment by rmrustem** [comment]
@joe-elliott I've changed the lib to the one suggested and force-pushed the changes. Please let me know if anything else is needed. Thanks!

**Comment by joe-elliott** [comment]
awesome, thanks!

**Pull request merged**
