### PR TITLE
only create dashboard if create value is true

### PR DESCRIPTION
**Pull request by izolight**

### CODE REVIEW

**Comment by joe-elliott** [comment]
Would this change the default behavior?  If someone upgraded their helm chart would this delete their dashboard?

**Comment by izolight** [comment]
It would only delete the dashboard if they changed the default dashboards.certManagerDashboard.create to false (which so far was a no-op). I would argue that changing this would imply wanting the dashboard not being installed.

**Comment by izolight** [comment]
@joe-elliott 
Is there anything preventing this getting merged?

**Comment by joe-elliott** [comment]
Apologies, let this one slip.  I didn't realize that 

```
.Values.dashboards.certManagerDashboard.create
```

already existed.

**Comment by joe-elliott** [comment]
Thanks for the contribution!  Now I have to remember how to build the helm chart :)

**Pull request merged**
